Modify 0021-RHBZ-548874-add-find-multipaths.patch fix bug where mpathconf wouldn't create a multpath.conf file unless one     already existed.

diff --git a/0021-RHBZ-548874-add-find-multipaths.patch b/0021-RHBZ-548874-add-find-multipaths.patch
--- a/0021-RHBZ-548874-add-find-multipaths.patch
+++ b/0021-RHBZ-548874-add-find-multipaths.patch
@@ -2,20 +2,20 @@
  libmultipath/Makefile    |    2 
  libmultipath/alias.c     |  152 ------------------------------
  libmultipath/alias.h     |    1 
- libmultipath/config.c    |    1 
+ libmultipath/config.c    |    5 -
  libmultipath/config.h    |    1 
  libmultipath/configure.c |   23 ++++
  libmultipath/defaults.h  |    2 
  libmultipath/dict.c      |   34 ++++++
- libmultipath/file.c      |  178 ++++++++++++++++++++++++++++++++++++
+ libmultipath/file.c      |  178 +++++++++++++++++++++++++++++++++++
  libmultipath/file.h      |   11 ++
  libmultipath/finder.c    |  150 ++++++++++++++++++++++++++++++
  libmultipath/finder.h    |   18 +++
  multipath/Makefile       |    2 
  multipath/main.c         |    2 
- multipath/mpathconf      |  232 +++++++++++++++++++++++++++++++++++++++++++++++
+ multipath/mpathconf      |  234 +++++++++++++++++++++++++++++++++++++++++++++++
  multipathd/main.c        |   27 +++--
- 16 files changed, 674 insertions(+), 162 deletions(-)
+ 16 files changed, 679 insertions(+), 163 deletions(-)
 
 Index: multipath-tools/libmultipath/alias.c
 ===================================================================
@@ -231,6 +231,20 @@ Index: multipath-tools/libmultipath/config.c
  
  	/*
  	 * preload default hwtable
+@@ -476,10 +477,12 @@ load_config (char * file)
+ 		}
+ 	} else {
+ 		condlog(0, "/etc/multipath.conf does not exist, blacklisting all devices.");
+-		condlog(0, "A default multipath.conf file is located at");
++		condlog(0, "A sample multipath.conf file is located at");
+ 		condlog(0,
+ "/usr/share/doc/device-mapper-multipath-%d.%d.%d/multipath.conf",
+ 			MULTIPATH_VERSION(VERSION_CODE));
++		condlog(0, 
++"You can run /sbin/mpathconf to create or modify /etc/multipath.conf");
+ 		conf->blist_devnode = vector_alloc();
+ 		if (!conf->blist_devnode) {
+ 			condlog(0, "cannot allocate blacklist\n");
 Index: multipath-tools/libmultipath/config.h
 ===================================================================
 --- multipath-tools.orig/libmultipath/config.h
@@ -882,7 +896,7 @@ Index: multipath-tools/multipath/mpathconf
 ===================================================================
 --- /dev/null
 +++ multipath-tools/multipath/mpathconf
-@@ -0,0 +1,232 @@
+@@ -0,0 +1,234 @@
 +#!/bin/sh
 +#
 +# Copyright (C) 2010 Red Hat, Inc. All rights reserved.
@@ -1102,10 +1116,12 @@ Index: multipath-tools/multipath/mpathconf
 +	fi
 +fi
 +
-+cp $CONFIGFILE $CONFIGFILE.old
-+if [ $? != 0 ]; then
-+	echo "failed to backup old config file, $CONFIGFILE not updated"
-+	exit 1
++if [ -f "$CONFIGFILE" ]; then
++	cp $CONFIGFILE $CONFIGFILE.old
++	if [ $? != 0 ]; then
++		echo "failed to backup old config file, $CONFIGFILE not updated"
++		exit 1
++	fi
 +fi
 +
 +cp $TMPFILE $CONFIGFILE
